export const FETCH_BUDGET_START = "FETCH_BUDGET_START";
export const FETCH_BUDGET_SUCCESS = "FETCH_BUDGET_SUCCESS";
export const FETCH_BUDGET_FAILED = "FETCH_BUDGET_FAILED";

export const FETCH_TRANSACTION_START = "FETCH_TRANSACTION_START";
export const FETCH_TRANSACTION_SUCCESS = "FETCH_TRANSACTION_SUCCESS";
export const FETCH_TRANSACTION_FAILED = "FETCH_TRANSACTION_FAILED";